# Generated by Django 2.2 on 2020-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
