# Generated by Django 2.2 on 2020-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_auto_20200416_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='sale_price',
            field=models.CharField(max_length=10),
        ),
    ]
