# Generated by Django 2.2 on 2020-03-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_auto_20200312_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no', models.TextField(max_length=10)),
                ('scheduled_departure', models.BooleanField()),
                ('scheduled_arrival', models.BooleanField()),
                ('departure_airport', models.TextField(max_length=100)),
                ('arrival_airport', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('aircraft_code', models.TextField(max_length=100)),
                ('actual_departure', models.TextField(max_length=100)),
                ('actual_arrival', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_id', models.PositiveIntegerField()),
                ('passenger_name', models.TextField(max_length=100)),
                ('contact_data', models.TextField(max_length=200)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.TextField()),
                ('amount', models.IntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flight')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Boarding_passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('seat_no', models.TextField(max_length=10)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flight')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
    ]
