# Generated by Django 2.2 on 2020-03-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0003_boarding_passes_flight_ticket_ticket_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_code', models.PositiveIntegerField()),
                ('model', models.TextField(max_length=100)),
                ('range', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('airport_name', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_arrival', to='airtrans.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_departure', to='airtrans.Airport'),
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.TextField(max_length=10)),
                ('fare_conditions', models.TextField(max_length=100)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
            ],
        ),
    ]
