# Generated by Django 2.2 on 2020-03-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0004_auto_20200312_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_arrival', to='airtrans.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_departure', to='airtrans.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_departure',
            field=models.TextField(max_length=100),
        ),
    ]
